<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>读Modern Statistics for Modern Biology随记</title>
  <meta name="description" content="学习Modern Statistics for Modern Biology记录" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="读Modern Statistics for Modern Biology随记" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="学习Modern Statistics for Modern Biology记录" />
  <meta name="github-repo" content="ecowang/M for M" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="读Modern Statistics for Modern Biology随记" />
  
  <meta name="twitter:description" content="学习Modern Statistics for Modern Biology记录" />
  

<meta name="author" content="王强" />


<meta name="date" content="2019-08-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="intro.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">读Modern Statistics for Modern Biology随记</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction 引言</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#section-1.1"><i class="fa fa-check"></i><b>1.1</b> 缘起</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#section-1.2"><i class="fa fa-check"></i><b>1.2</b> 原书目标</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#section-1.3"><i class="fa fa-check"></i><b>1.3</b> 本书特点</a><ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#section-1.3.1"><i class="fa fa-check"></i><b>1.3.1</b> 统计江湖的套路</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#section-1.3.2"><i class="fa fa-check"></i><b>1.3.2</b> 统计的常见概念和生命学科特殊性</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#section-1.3.3"><i class="fa fa-check"></i><b>1.3.3</b> 原书中主要内容</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#section-1.4"><i class="fa fa-check"></i><b>1.4</b> 需要的计算机技能</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Generative Models for Discrete Data 广义模型和离散数据</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#section-2.1"><i class="fa fa-check"></i><b>2.1</b> 回顾关于概率的基础知识</a><ul>
<li class="chapter" data-level="2.1.1" data-path="intro.html"><a href="intro.html#section-2.1.1"><i class="fa fa-check"></i><b>2.1.1</b> 概率论与数理统计</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="statistical-modeling.html"><a href="statistical-modeling.html"><i class="fa fa-check"></i><b>3</b> Statistical Modeling</a></li>
<li class="chapter" data-level="4" data-path="high-quality-graphics-in-r.html"><a href="high-quality-graphics-in-r.html"><i class="fa fa-check"></i><b>4</b> High-Quality Graphics in R</a></li>
<li class="chapter" data-level="5" data-path="mixture-models.html"><a href="mixture-models.html"><i class="fa fa-check"></i><b>5</b> Mixture Models</a></li>
<li class="chapter" data-level="6" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>6</b> Clustering</a></li>
<li class="chapter" data-level="7" data-path="testing.html"><a href="testing.html"><i class="fa fa-check"></i><b>7</b> Testing</a></li>
<li class="chapter" data-level="8" data-path="multivariate-analysis.html"><a href="multivariate-analysis.html"><i class="fa fa-check"></i><b>8</b> Multivariate Analysis</a></li>
<li class="chapter" data-level="9" data-path="high-throughput-count-data.html"><a href="high-throughput-count-data.html"><i class="fa fa-check"></i><b>9</b> High-Throughput Count Data</a></li>
<li class="chapter" data-level="10" data-path="multivariate-methods-for-heterogeneous-data.html"><a href="multivariate-methods-for-heterogeneous-data.html"><i class="fa fa-check"></i><b>10</b> Multivariate Methods for Heterogeneous Data</a></li>
<li class="chapter" data-level="11" data-path="networks-and-trees.html"><a href="networks-and-trees.html"><i class="fa fa-check"></i><b>11</b> Networks and Trees</a></li>
<li class="chapter" data-level="12" data-path="image-data.html"><a href="image-data.html"><i class="fa fa-check"></i><b>12</b> Image Data</a></li>
<li class="chapter" data-level="13" data-path="supervised-learning.html"><a href="supervised-learning.html"><i class="fa fa-check"></i><b>13</b> Supervised Learning</a></li>
<li class="chapter" data-level="14" data-path="design-of-high-throughput-experiments-and-their-analyses.html"><a href="design-of-high-throughput-experiments-and-their-analyses.html"><i class="fa fa-check"></i><b>14</b> Design of High-Throughput Experiments and Their Analyses</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/ecowang/MforM" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">读Modern Statistics for Modern Biology随记</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">读Modern Statistics for Modern Biology随记</h1>
<p class="author"><em>王强</em></p>
<p class="date"><em>2019-08-16</em></p>
</div>
<div id="introduction-" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Introduction 引言</h1>
<div id="section-1.1" class="section level2">
<h2><span class="header-section-number">1.1</span> 缘起</h2>
<p><a href="http://web.stanford.edu/class/bios221/book/index.html">Modern Statistics for Modern Biology</a>这本书，是斯坦福大学<a href="https://profiles.stanford.edu/susan-holmes">Susan P. Holmes</a> 教授和 <a href="https://www.embl.org/">欧洲分子生物实验室</a>的<a href="https://www.huber.embl.de/">Wolfgang Huber</a> 教授共同编写的。两位都是大牛，追求他们的文章可以发现学科发展趋势的那种。</p>
<p>这本书2018年才出版，全文上网，还有配套的练习代码、数据，是很新鲜的学习材料。Holme教授在斯坦福大学暑期学校也教<a href="http://web.stanford.edu/class/bios221/about.html">这门课</a>，课程时长才<a href="http://web.stanford.edu/class/bios221/TimesCourse.html">十来天</a>。我本想找找有没有视频跟着学学，不过一直没找到，只好跟着书学，并在这里写一些记录。</p>
</div>
<div id="section-1.2" class="section level2">
<h2><span class="header-section-number">1.2</span> 原书目标</h2>
<blockquote>
<p>The aim of this book is to enable scientists working in biological research to quickly learn many of the important ideas and methods that they need to make the best of their experiments and of other available data.</p>
</blockquote>
<p>原书的目的是让生命口的工作者<strong>很快地</strong>学会能用于其实验和数据的重要理念和方法，这也是我想获取的技能。感觉强大的数据分析能力是一把手术刀，能突破学科壁垒，快速了解关键问题，并产出相对专业的成果；又如同包装设计师，一样的研究结果，用一些更加深入的统计工具来分析，或者以更加直观的统计图来呈现，会让人更有好感，更值得信赖、更容易接受。好像同一个小伙，了解女孩想事儿的套路了，则什么类型的姑娘都容易聊起来；再好好捯饬下自己，更容易获得她们的欣赏……大雾。</p>
<p>学习本书需要什么样的知识背景呢？我的感觉，基本生命专业的本科生都可以，有实际需求的最好。因为它并不涉及系统的统计背景知识，主要是对工具使用方法的学习，说白了就是培训“工匠技能”，有点数学基本知识、生物学背景再了解点R语言的皮毛，上就是了。不太熟的，上多了也就熟了。</p>
<p>所以，解决实际问题，也是本人的学习导向。首先要明确解决的问题是什么。有时候把问题定义清楚了，也就解决一半了。定义问题和解决问题的过程包括：</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>知道哪些前提数据</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>前提数据的表现形式、存储格式等</li>
</ol></li>
<li><ol start="3" style="list-style-type: decimal">
<li>要分析的目标、方向</li>
</ol></li>
<li><ol start="4" style="list-style-type: decimal">
<li>使用的工具（模型、包、函数）</li>
</ol></li>
<li><ol start="5" style="list-style-type: decimal">
<li>结果的意义、表现形式（图、表、显著性等）</li>
</ol></li>
</ul>
<p>知道前提数据，并了解它们的表现形式，是很重要的环节。Susan在书中提出应对数据的<strong>差异性</strong>（<a href="http://web.stanford.edu/class/bios221/book/introduction.html">The challenge: heterogeneity</a>），也说明生命学科不同细分领域产生数据的多样性和差异性令人挠头。当然R语言作为一种语言，应对这种差异性再合适不过——语言嘛，见人说人话见鬼说鬼话就是了，前提是我们要大致了解这些神神鬼鬼，并学会一定的说话套路。</p>
</div>
<div id="section-1.3" class="section level2">
<h2><span class="header-section-number">1.3</span> 本书特点</h2>
<div id="section-1.3.1" class="section level3">
<h3><span class="header-section-number">1.3.1</span> 统计江湖的套路</h3>
<p>首先作者放着这么一张图，统计学经典流程：做出原假设、实验检验、计算显著性（p值）、得出结论（原假设是否可靠）。并在图上有所创新，把原假设概念拓展到模型的宽度。</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-1"></span>
<img src="http://web.stanford.edu/class/bios221/book/images/FisherParadigm.png" alt="这是Fisher提出的原假设检验过程。本书中可以把Hypothesis H0，想象成要拟合的模型，分析过程类似" width="25%" />
<p class="caption">
Figure 1.1: 这是Fisher提出的原假设检验过程。本书中可以把Hypothesis H0，想象成要拟合的模型，分析过程类似
</p>
</div>
<p>然而这个图并不能涵盖本书内容，只是出来露个脸，可能作为一个统计的书，不提一下这个经典的理论有点缺乏正义性吧。</p>
<p>然后谈及对统计工作的划分角度，从大牛的视角开始<span class="citation">(Tukey <a href="#ref-tukey_exploratory_1977">1977</a>)</span>，曾经分成这么两类:</p>
<blockquote>
<ul>
<li>探索分析 exploratory data analysis (EDA) 。</li>
<li>实证分析 confirmatory data analyses (CDA)。</li>
</ul>
</blockquote>
<p>原文中有对这两种方法的解释，但感觉说的不清不楚的，下面这个比较清晰 <span class="citation">(Karageorgiou <a href="#ref-Karageorgiou_2011">2011</a>)</span>。</p>
<blockquote>
<p>Exploratory Data Analysis (EDA) and Confirmatory Data Analysis (CDA) are two statistical methods widely used in scientific research. They are typically applied in sequence: first, EDA helps form a model or a hypothesis to be tested, and then CDA provides the tools to confirm if that model or hypothesis holds true.</p>
</blockquote>
<p>基本上，EDA好像公安，遇见案子了要明确问题、搜集线索、整理证据、得出推论，而CDA就是检查院，要对公安得出的结论，以及整个证据链，进行检验，明确是否接受这个结论。接受了就送交法院，不接受呢，就得打回去，重新办理。</p>
</div>
<div id="section-1.3.2" class="section level3">
<h3><span class="header-section-number">1.3.2</span> 统计的常见概念和生命学科特殊性</h3>
<p>原书中在EDA和CDA后，直接介绍生命学科搞统计遇到的的大 <em>p</em> 小 <em>n</em> 问题，介绍其如何不利于建模和得出推论。这里稍微扩展一点，明确一点概念和普通的建模，便于后面对照理解。</p>
<div id="-p--n" class="section level4">
<h4><span class="header-section-number">1.3.2.1</span> 关于 <em>p</em> 和 <em>n</em></h4>
<p>先明确一下统计学常见的 <em>p</em> 和 <em>n</em> 是什么。 统计分析之前要有数据整理的过程，一般要把原始数据按 <code>case/observation/个体/测量对象</code> 和 <code>variable/属性/变量</code> 按照<strong>行</strong>和<strong>列</strong>进行整理。整理好的数据，有多少个<code>case/个体（测量对象）</code>，<em>n</em> 就是多少；有多少<code>variable/属性（变量）</code>，<em>p</em> 就是多少。收集数据的时候也要有这个意识，好的原始数据结构会减少后续整理的麻烦。</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-2"></span>
<img src="static/Users/eco/M%20for%20M/index_files/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-08-13%20%E4%B8%8B%E5%8D%884.23.00.png" alt="Excel中的示例，行为case，列为variable，这样放能直接应用**数据透视表**"  />
<p class="caption">
Figure 1.2: Excel中的示例，行为case，列为variable，这样放能直接应用<strong>数据透视表</strong>
</p>
</div>
</div>
<div id="section-1.3.2.2" class="section level4">
<h4><span class="header-section-number">1.3.2.2</span> 一个普通的建模</h4>
<p>从根上讲，所谓建模，其实就是找到要分析数据的，对我们有意义的某些方面的规律，并用公式表达出来；有时候需要把提取出来的规律应用到新的数据，得出预测的结果。Hadley把建模分为2类 <span class="citation">(Grolemund and Wickham <a href="#ref-grolemund">2019</a>)</span> <del>才发现这本书Hadley居然不是第一作者</del>：</p>
<table>
<thead>
<tr class="header">
<th>模型类别</th>
<th>别称1</th>
<th>别称2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>* 预测模型</td>
<td>“predictive” models</td>
<td>supervised models</td>
</tr>
<tr class="even">
<td>* 数据分析模型</td>
<td>“data discovery” models</td>
<td>unsupervised models</td>
</tr>
</tbody>
</table>
<p>预测模型好理解，我做个线性回归，这个回归模型肯定能在一定范围内预测趋势。可数据分析模型到底是啥玩意，咱也不知道，咱也搜不着，data discovery 从搜索结果看指向很宽泛的数据分析领域，unsupervised model呢，又和deep learning 经常出现在一块。所以我可以先把这个概念放一边——肯定不是啥严谨的东西，估计是主成分分析、聚类分析等不能外推规律的方法。 Hadley <a href="https://r4ds.had.co.nz/model-intro.html">书中</a>也只介绍预测模型，下面摘一个简单的例子。</p>
<pre><code>## Registered S3 methods overwritten by &#39;ggplot2&#39;:
##   method         from 
##   [.quosures     rlang
##   c.quosures     rlang
##   print.quosures rlang</code></pre>
<pre><code>## ── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ tibble  2.1.3     ✔ purrr   0.3.2
## ✔ tidyr   0.8.3     ✔ dplyr   0.8.1
## ✔ readr   1.3.1     ✔ stringr 1.4.0
## ✔ tibble  2.1.3     ✔ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-4">Table 1.1: </span>modelr包中的<code>sim1</code>，simulation1的意思，如果觉得不好想象，可以当成x是年龄，y是体重</caption>
<thead>
<tr class="header">
<th align="right">x</th>
<th align="right">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">4.199913</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">7.510634</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="right">2.125473</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">8.988857</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">10.243105</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">11.296823</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">7.356365</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="right">10.505349</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">10.511601</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">12.434589</td>
</tr>
<tr class="odd">
<td align="right">4</td>
<td align="right">11.892601</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">14.257964</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">19.130050</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">11.738021</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">16.024854</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">13.273977</td>
</tr>
<tr class="odd">
<td align="right">6</td>
<td align="right">15.955975</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">16.894796</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">20.085993</td>
</tr>
<tr class="even">
<td align="right">7</td>
<td align="right">17.171850</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">19.936309</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">21.725903</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">18.390913</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">22.475553</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">26.777010</td>
</tr>
<tr class="even">
<td align="right">9</td>
<td align="right">22.805110</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">21.128305</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">24.968099</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="right">23.346422</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">21.975201</td>
</tr>
</tbody>
</table>
<p>这组数据拿到手里，要建模，先做个图看看。</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-5"></span>
<img src="M-for-M_files/figure-html/unnamed-chunk-5-1.png" alt="拿眼一看就有明显的线性关系" width="672" />
<p class="caption">
Figure 1.3: 拿眼一看就有明显的线性关系
</p>
</div>
<p>然后要找到这个线性关系。高中数学告诉我们可以用 <span class="math inline">\(Y = aX + b\)</span> 的形式表现这个线，然后就要找到 <span class="math inline">\(a\)</span> 和 <span class="math inline">\(b\)</span> 。实现方法很简单：</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">sim1_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x, <span class="dt">data =</span> sim1)</a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="kw">coef</span>(sim1_mod)</a></code></pre></div>
<pre><code>## (Intercept)           x 
##    4.220822    2.051533</code></pre>
<p>得到线性模型 <span class="math inline">\(Y = 2.051533 X + 4.220822\)</span> 。 如果用图形表现，可以这样实现。</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">ggplot</span>(sim1, <span class="kw">aes</span>(x, y)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb7-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-7"></span>
<img src="M-for-M_files/figure-html/unnamed-chunk-7-1.png" alt="线性模型的图形表现" width="672" />
<p class="caption">
Figure 1.4: 线性模型的图形表现
</p>
</div>
<p>这样一个简单模型就出来了，它充分归纳了已有数据的规律，也能推测数据之外的一定范围，比如可以推测11岁的时候大概有多重，这也是统计的目的所在——通过已知，预测未知。这里要注意，本数据中 <em>p</em> 是很少的（就俩，<span class="math inline">\(x\)</span> 和 <span class="math inline">\(y\)</span> ）， <em>n</em> 是很多的，有30个，要建立模型，是需要确定 <em>p</em> 之间的系数的。</p>
</div>
<div id="-p--n-" class="section level4">
<h4><span class="header-section-number">1.3.2.3</span> 生命学科的大 <em>p</em> 小 <em>n</em> 问题</h4>
<p>生命学科由于其特点，经常呈现出和刚才举例完全相反的数据。比如200个病人的基因样本，可能每个病人都有20000个基因。想想刚才的 <span class="math inline">\(Y = 2.051533 X + 4.220822\)</span> ，如果想建立线性模型，理论上这个公式要扩充到20000个参数。</p>
<p>统计学家目前通过两种方向解决这个问题：</p>
<ul>
<li>人工筛选变量（sparsity principle），把没用都的变量系数提前定义成0，或者接近0 <span class="citation">(Hastie, Tibshirani, and Friedman <a href="#ref-hastie_elements_2016">2016</a>)</span>。</li>
<li>贝叶斯经验方法（empirical Bayes），是sparsity principle的扩展（generalization），该方法认为“组间，或者性状之间，总有某些，甚至全部变量应该是相同或类似的”，然后发展出一系列方法，详细了解可参考 <span class="citation">Speed (<a href="#ref-speed_large-scale_2011">2011</a>)</span> 。</li>
</ul>
<p>此外，原书中模拟（Simulations）的内容比较多。通过模拟一些数据练手，摆脱已有分析套路的局限，磨好屠龙刀，争取能更贴近实际的问题。</p>
</div>
</div>
<div id="section-1.3.3" class="section level3">
<h3><span class="header-section-number">1.3.3</span> 原书中主要内容</h3>
<p>基于上述问题和发展出来的分析方法，原书中均有涉及，处理数据包括RNA序列，细胞流式分析，种丰富度，图像数据和单细胞测量等（ RNA-Seq, flow-cytometry, taxa abundances, imaging data and single cell measurements)。作者贴心的说明学习本书不需要统计学背景（assume no prior training in statistics），但得了解一点R的知识，更重要的是愿意折腾——代码、公式、数学分析等。</p>
<ol style="list-style-type: decimal">
<li><p><strong>第一章 广义模型和离散数据/Generative Models for Discrete Data</strong><br />
这一章先介绍简单模型的建立，但和刚才直接做个线性模型不同，本章从概率理论出发讲模型。概率和基因序列分析关系比较密切，结合免疫和DNA分析例子，介绍二项式/binomial, 多项式/multinomial 和泊松随机分布（变量）/ Poisson random variables。</p></li>
<li><p><strong>第二章 统计建模 Statistical Modeling</strong><br />
本章和上一章的关系在于，上一章看特定模型下数据长得什么样，这一章给定数据，看能应用什么模型，这才是建模的常规工作。</p></li>
<li><p><strong>第三章 R语言高质量作图 High Quality Graphics in R</strong><br />
讲了ggplot2，还有一些数据转化、作图语法方面的内容。</p></li>
<li><p><strong>第四章 混合模型 Mixture Models</strong><br />
数据肯定不会都顺顺当当的按模式分布，要刻画真实的数据，要把简单的模型进行组合，做成混合模型来反映实际。也包含一些数据转化的内容，这里转化要注意的是保证信息的稳定。（appropriate variance stabilizing transformations）</p></li>
<li><p><strong>第五章 聚类 Clustering</strong><br />
The large, matrix-like ( <span class="math inline">\(n×p\)</span> ) datasets in biology naturally lend themselves to clustering。数据只要能计算出Matrix-like的距离来，都可以应用聚类，这一章可能会大量介绍如何对不同类型的数据计算距离吧。</p></li>
<li><p><strong>第七章 多元统计 Multivariate Analysis<br />
第九章 针对乱糟糟数据的多元方法 Multivariate methods for heterogeneous data</strong><br />
从逻辑上说，这两章虽然不挨着，但都是所谓EDA的范畴，也属于data discovery models或 unsupervised models。 第七章介绍了以主成分分析（PCA）为主线的多元统计方法，第九章深入应用这些方法，涉及非线性、分类变量、同一观测多重测定（multiple assays recorded on the same observational units）等</p></li>
<li><p><strong>第六章 检验 testing</strong><br />
检验可以针对假说、可以对模型，验证其是否合理，是否显著。介绍中说会实际检验一个 <span class="math inline">\(n × p\)</span> 的数据集中，哪个基因或性状与某种疾病或其他表现是有联系的。但传统的显著性指标（也就是p值）不好使，所以要好好研究下多元检验（multiple testing）。</p></li>
<li><p><strong>第八章 高通量计数数据 High-Throughput Count Data</strong><br />
统计学一大利器是方差分解（variance decomposition），或曰方差分析（ANOVA）。本章以线性模型和广义线性模型的套路，分析RNA序列数据。分析也会涉及计数数据以及对稳健性（robustness）的讨论。</p></li>
<li><p><strong>第十章 网和树 Networks and Trees</strong><br />
据说生命科学中除了从进化的角度分析问题，其他啥都没多少意义。进化关系在系统发育树中体现，本章探索网和树的应用。</p></li>
<li><p><strong>第十一章 图像数据 Image data</strong><br />
在图像中提取特征数据，并进行分析，也是EDA的范畴。本章学习图像数据读写操作，分析方法等。</p></li>
<li><p><strong>第十二章 监督式学习 Supervised Leaning</strong><br />
属于统计学习的范畴（不知道算不算机器学习），如训练一个公式，基于某些多维特征向量分辨不同对象。从简单低维特征向量和线性方法开始，也探索高纬度分类设计。 <del>囧。。。说的啥啊这是</del>。</p></li>
<li><p><strong>第十三章 高通量实验设计及分析 Design of High Throughput Experiments and their Analyses</strong><br />
介绍好的实验设计和相关数据分析，会对书中所学方法综合运用。</p></li>
</ol>
</div>
</div>
<div id="section-1.4" class="section level2">
<h2><span class="header-section-number">1.4</span> 需要的计算机技能</h2>
<p>通过对原书内容的概览，可以发现分析对象、角度、方法多种多样，要满足需求，要用 R 和 Bioconductor。</p>
<p>R是一种语言，一种为统计而生的语言；Bioconductor是基于R语言项目，专门提供搞生物数据的工具。要开始学习R语言有海量的资源，原书作者建议从 <a href="http://r4ds.had.co.nz">R for Data Science</a> 开始学习，我也这么建议，因为Hadley确实是大神。 原书中用到的ggplot2， dplyr包，都是他写的。</p>
<p>另一个大神大家也可以关注，是中国人，现在美国，人大毕业，Rstudio主力程序员——<a href="https://yihui.name/">谢益辉</a>。作图和排版用的很多包，blogdown，bookdown，knitr等，都是他写的。包括本人现在写的这个记录，也是用bookdown写的，我的个人网站也是用的他的模板。</p>
<p>从这样的学科头部学者身上学习，会更有高度，更系统，当然也会更有难度，更需要学习能力。</p>
<p>Modern Statistics for Modern Biology的作者也是学科头部学者，而且这本书把数据代码都给出来，便于练习，是很好的学习材料。</p>
<p>所以还等什么呢，下载<a href="https://www.r-project.org/">R</a>，下载<a href="https://www.rstudio.com/">Rstudio</a>，安装需要的包，开动吧。</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-grolemund">
<p>Grolemund, Garrett, and Hadley Wickham. 2019. <em>R for Data Science</em>. <a href="https://r4ds.had.co.nz/">https://r4ds.had.co.nz/</a>.</p>
</div>
<div id="ref-hastie_elements_2016">
<p>Hastie, Trevor, Robert Tibshirani, and Jerome Friedman. 2016. <em>The Elements of Statistical Learning: Data Mining, Inference, and Prediction, Second Edition</em>. 2nd edition. New York, NY: Springer.</p>
</div>
<div id="ref-Karageorgiou_2011">
<p>Karageorgiou, Elissaios. 2011. “The Logic of Exploratory and Confirmatory Data Analysis.” <em>Cognitive Critique</em>, January, 35–48.</p>
</div>
<div id="ref-speed_large-scale_2011">
<p>Speed, Terry. 2011. “Large-Scale Inference: Empirical Bayes Methods for Estimation, Testing, and Prediction by Bradley Efron.” <em>International Statistical Review</em> 79 (1): 126–27. <a href="https://doi.org/10.1111/j.1751-5823.2011.00134_13.x">https://doi.org/10.1111/j.1751-5823.2011.00134_13.x</a>.</p>
</div>
<div id="ref-tukey_exploratory_1977">
<p>Tukey, John W. 1977. <em>Exploratory Data Analysis</em>. Addison-Wesley Pub. Co.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="intro.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ecowang/MforM/edit/master/index.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["M-for-M.pdf", "M-for-M.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
